const data = {
  products: [
    {
      name: "Nike Slim Shoes",
      slug: "nike-slim-shoes",
      category: "Shoes",
      price: 120,
      countinstock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
      image: "/images/img1.jpg",
    },
    {
      name: "addidas Slim Shoes",
      slug: "addidas-slim-shoes",
      category: "Shoes",
      price: 150,
      countinstock: 10,
      brand: "addidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
      image: "/images/img4.jpg",
    },
    {
      name: "Servis Slim Shoes",
      slug: "service-slim-shoes",
      category: "Shoes",
      price: 90,
      countinstock: 10,
      brand: "Servis",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
      image: "/images/img2.jpg",
    },
    {
      name: "Bata Slim Shoes",
      slug: "bata-slim-shoes",
      category: "Shoes",
      price: 80,
      countinstock: 10,
      brand: "Bata",
      rating: 4.5,
      numReviews: 10,
      description: "high quality products",
      image: "/images/img5.jpg",
    },
  ],
};

export default data;
